repos:
- repo: https://github.com/markdownlint/markdownlint
  rev: e31711c0db57df9b350fbaeaae6de745972f3e66
  hooks:
  - id: markdownlint_docker
    name: Markdown linting
    exclude: |
      (?x)^(
          docs/CONTRIBUTORS.md
      )$
- repo: https://github.com/rhysd/actionlint
  rev: 393031adb9afb225ee52ae2ccd7a5af5525e03e8
  hooks:
  - id: actionlint
    name: Lint GitHub Actions workflow files
    description: Runs actionlint to lint GitHub Actions workflow files
    language: golang
    types: ["yaml"]
    files: ^\.github/workflows/
    entry: actionlint
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: v1.23.1
  hooks:
    - id: zizmor
