repos:
- repo: https://github.com/markdownlint/markdownlint
  rev: e31711c0db57df9b350fbaeaae6de745972f3e66
  hooks:
  - id: markdownlint_docker
    name: Markdown linting
    exclude: |
      (?x)^(
          docs/CONTRIBUTORS.md
      )$
- repo: local
  hooks:
  - id: dep-graph-gen
    name: Generate dependency graph
    language: system
    entry: |
      make docs/assets/project-deps.png
