repos:
- repo: https://github.com/markdownlint/markdownlint
  rev: e31711c0db57df9b350fbaeaae6de745972f3e66
  hooks:
  - id: markdownlint_docker
    name: Markdown linting
    exclude: |
      (?x)^(
          docs/CONTRIBUTORS.md
      )$
