strict: true

site_name: "kubernetes-el: Kubernetes client for Emacs"
site_description: Kubernetes client for Emacs
site_url: https://kubernetes-el.github.io/kubernetes-el

repo_name: kubernetes-el/kubernetes-el
repo_url: https://github.com/kubernetes-el/kubernetes-el

nav:
  - Home: index.md
  - Getting Started:
      - getting-started/index.md
      - Tutorials:
          - getting-started/tutorials/index.md
          - Feature Overview: getting-started/tutorials/0-feature-overview.md
  - How-To: how-to.md
  - References:
      - references/index.md
      - Changelog: CHANGELOG.md
      - Compatibility: references/compatibility.md
  - Contributors Guide:
      - contributing/index.md

theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - smarty
  - tables
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
