name: Docs
on:
  push:
    branches:
      - master
      - jjin/docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: pip install mkdocs-material

      - name: CHANGELOG.org -> CHANGELOG.md
        uses: docker://pandoc/core:2.9
        with:
          args: -s CHANGELOG.org -t gfm -o docs/CHANGELOG.md
      - run: cp Readme.md docs/README.md

      - run: mkdocs gh-deploy --force
